# Generated by Django 2.2 on 2020-07-13 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_id', models.CharField(max_length=255)),
                ('stop_sequence', models.CharField(max_length=255)),
                ('direction_id', models.CharField(max_length=255)),
                ('route_id', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'route_relation',
            },
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('stop_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('stop_name', models.CharField(max_length=255)),
                ('stop_lat', models.CharField(max_length=255)),
                ('stop_lon', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'stops',
            },
        ),
    ]
